# Generated by Django 4.1.7 on 2023-03-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productbrands_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
